### PR TITLE
add repository dispatch in publish-docs

### PR DESCRIPTION
**Pull request by tsirlucas**

### CODE REVIEW

**Review by sideeffffect — APPROVED** [review]
Looks fine to me, but I have to admit I don't know the context.
Or would you @tsirlucas like to wait for @lgmyrek 's review?

**Comment by tsirlucas** [comment]
Lets wait just in case. This will require BE to provide a PAT when calling this action so its a good idea to let the person who created it add a review

**Comment by tkroman** [comment]
why is this an input instead of an env var?

**Comment by tsirlucas** [comment]
i wanted to make sure its visible that this is required. also if someone miss this pr and the action starts failing, having a fail message telling its a missing required field will be easier than some request failing with 401

**Comment by renanbandeira** [comment]
> i wanted to make sure its visible that this is required. also if someone miss this pr and the action starts failing, having a fail message telling its a missing required field will be easier than some request failing with 401

I agree with @tkroman . If we add the PAT as a github env var, we won't need to define this in every repo and whenever we need to update, we would update in one place only

**Comment by tsirlucas** [comment]
> I agree with @tkroman . If we add the PAT as a github env var, we won't need to define this in every repo and whenever we need to update, we would update in one place only
do we have org-level env vars?

**Comment by renanbandeira** [comment]
> > I agree with @tkroman . If we add the PAT as a github env var, we won't need to define this in every repo and whenever we need to update, we would update in one place only
> 
> do we have org-level env vars?
Yes, we have some of them

image

**Comment by tsirlucas** [comment]
Perfect! Will update

**Comment by renanbandeira** [comment]
@tsirlucas we have one called `REPOSITORY_DISPATCH_PAT`

**Comment by fernandonogueira** [comment]
Hey guys. Which account does this PAT belong to?

**Review by lgmyrek — APPROVED** [review]

**Comment by fernandonogueira** [comment]
Can I recreate the PAT with a bot account, then? 😆 
Which permissions are needed?

**Comment by fernandonogueira** [comment]
Done. I just updated the organization token with a new value. I used the `chilipiper-gitops-prod` account to create it. 
So, if you have issues, please make sure this user has permission in the repository.

**Comment by fernandonogueira** [comment]
> i wanted to make sure its visible that this is required. also if someone miss this pr and the action starts failing, having a fail message telling its a missing required field will be easier than some request failing with 401

Taking advantage that I'm already here, I also prefer to use input + env var because it decreases the coupling of GH Action.

**Pull request merged**
